x=int(input("First number: "))
y=int(input("Second number: "))
z=int(input("Third number: "))
n=int(input("Limitation on Sum: "))
print([[i,j,k] for i in range(0,x+1) for j in range(0,y+1) for k in range(0,z+1) if i+j+k!=n])
